### ISSUE TITLE
Wrong package name in generated mock

### ISSUE THREAD

**Issue by jriquelme** [xeger/mongoose#3]
mongoose doesn't seem to support packages where the "directory name" and declared package (in the source code) don't match, like in this case: https://github.com/larixsource/go-schema-registry.

After run `mongoose -mock=testify .`, the heading of the resuling file (mock_registry.go) is `package go-schema-registry` instead of `package schemaregistry`.

**Comment by xeger** [comment]
Argh! Sorry I didn't see your issue earlier; I'd forgotten to watch my own repository. :(

I will look into this tonight.
